stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/tweets_suspect.csv
    outs:
      - data/tweets_preprocessed.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/tweets_preprocessed.csv
    outs:
      - models/best_model.pkl
      - models/tfidf_vectorizer.pkl
    metrics:
      - models/results.json:
          cache: false

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/results.json
